### ISSUE TITLE
'File' object has no attribute 'root'

### ISSUE THREAD

**Issue by Remyzk** [molneya/indev-level-converter#8]
I tried converting an indev world file but when I tried I got this error:

Could not convert indev.mclevel: 'File' object has no attribute 'root'
This gets fixed by just removing the .root from nbt_file.root

**Comment by molneya** [comment]
yes, this is a problem because i used an older version of nbtlib to create
this program initially. if you see the readme i say to install an older
version of nbtlib to make this work. i have not really seen how the new
version works so ill need to do some more testing to make sure everything
works correctly with the new version.
